route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 5m
  receiver: 'email'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'email'
  email_configs:
    - to: 'itmonitoring@volza.com'
      from: 'volza.alert@gmail.com'
      smarthost: smtp.gmail.com:587
      auth_username: 'volza.alert@gmail.com'
      auth_identity: 'volza.alert@gmail.com'
      auth_password: 'juxzrpcnwcrrmhvv'
      send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
